name = "hono-todo"
pages_build_output_dir = "./dist"

[vars]
MY_NAME = "Hono"

[[kv_namespaces]]
binding = "MY_KV"
id = "ff1fbe58185f49e2b34ea990f3c33055"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"